version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
before_build:
- ps: >-
    dotnet restore .\NSql.sln
build:
  project: .\NSql.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
before_test:
  - ps: >-
    dotnet restore .\NSql.sln
test_script:
- cmd: >-
    cd .\src\NSql.Test
    dotnet restore .\NSql.Test.
    dotnet test -f %framework% -s test.runsettings
cache:
  - $HOME/.nuget/packages